### ISSUE TITLE
Recurring contributions get incorrect receipts

### ISSUE THREAD

**Issue by martinh-pw** [systopia/de.systopia.donrec#104] opened 2020-05-26 16:25 UTC
Hi there, we are seeing an issue where contributions are showing up as receipted, but we did not receipt them. Here's a breakdown of what we believe we are seeing.

This case happens when there are recurring contributions. It only happens when the original contribution has already been receipted (which had worked properly).

When the later contributions are made, they get added to the old receipt that was previously created. These show up as duplicate lines on the existing receipt. That is, there is a new entry created in the zwb_donation_receipt_item custom field table for this new contribution.

For example, say a recurring (monthly) contribution starts 2019-Dec-05. On 2020-Jan-01 we generate all the receipts for the 2019 year (works properly). Then 2020-Jan-05 the recurring payment is made. This new contribution becomes automatically added to the old receipt (it shows up with date 2019-Dec-05, so now there are two on this date). The same thing happens again on Feb-05, Mar-05, etc.

This was on WordPress 5.4.1, CiviCRM 5.24.5. Extension version shows as 1.6-dev and I believe is about 1 year old.

What I believe is happening is that Civi is simply duplicating the entire contribution and the custom fields are getting copied along. Some possible solutions:
1. Use hook_civicrm_custom and prevent the copy from saving. This is probably ideal but depends on detecting properly when this is happening, as opposed to a valid save.
1. Allow the copy to save but instead detect duplicates later and do something about them (might be easier but probably less ideal).

**Comment by bjendres** [comment] 2020-05-27 06:42
That sounds like a pretty bad problem, thanks for reporting!

My suspicion is the following: I remember that in the Barcelona sprint we were talking about improving the generation of recurring contribution installments by adding a 'template' contribution (marked in the ``is_template`` field), the fields of which would automatically be copied into any new installment. If they implemented this in a way that it now automatically copies *all* custom fields (including the receipt information) to any new installment, that would be a disaster :/

@martinh-pw: Could you have a look at your system and see if anything like this might be going on?

Also: You might also want to upgrade your donation receipts extension, there's a couple of known issues with that version and CiviCRM ``5.19``+

**Comment by martinh-pw** [comment] 2020-05-27 11:51
Hi @bjendres, the behavior you're describing sounds like basically what we are seeing, i.e. that the new contribution is basically a copy of an older one (including all custom fields). However this query returns 0 on our db: `SELECT * FROM civicrm_contribution where is_template=1`

**Comment by bjendres** [comment] 2020-06-02 07:28
@jensschuppe Could you please see if you can reproduce this behaviour on a CiviCRM ``5.24.5``. Potentially where the contribution (and/or recurring contribution) has custom fields.

**Comment by jensschuppe** [comment] 2020-06-05 11:31
I could not reproduce the issue on a CiviCRM 5.24.5, here's what I did:

1. Create a recurring contribution using the API explorer: `ContributionRecur.create` with a status "Pending"
2. Create a contribution that belongs to the recurring contribution using the API explorer: `Contribution.create`
3. Issue a donation receipt for the contact, including the contribution
4. Create another contribution that belongs to the recurring contribution (`Contribution.create`)

Result ist that the second contribution is _not_ receipted (expected behavior).

**Comment by jensschuppe** [comment] 2020-06-05 12:28
Seens related to civicrm/civicrm-core/pull/17454

**Comment by bjendres** [comment] 2020-06-05 12:51
@martinh-pw as @jensschuppe pointed out this seems to be a bug in CiviCRM core, that copies all custom fields (including the 'is receipted' information) to a new installment when the payment processor uses ``Contribution.repeattransaction``.

We'll try to add mitigation/cleanup code to the extension next week (see #105), would you be able to test?

**Comment by jensschuppe** [comment] 2020-06-05 12:54
@martinh-pw Can you also confirm that it is related to CiviCRM payment processors (i.e. PayPal or somthing that uses the iATS Payments extension) - just to be clear about the cause?

**Comment by martinh-pw** [comment] 2020-06-05 14:21
Thanks @jensschuppe and @bjendres , this is great having these clarifications! 

Yes I can confirm the cases we're seeing are specifically for recurring payments processed via iATS, using the com.iatspayments.civicrm extension.

Yes, can test your changes for sure, although it might take a few days. I know someone customized the extension previously and I need to figure out what they did before I can update it.

**Comment by jensschuppe** [comment] 2020-06-16 10:13
@martinh-pw You can test the implemented mitigation with [2.0-beta3](https://github.com/systopia/de.systopia.donrec/releases/tag/2.0-beta3).

Please report back here whether there are still issues with that.

**Comment by jensschuppe** [comment] 2020-09-01 08:22
@martinh-pw Can you confirm the mitigation implemented in 2.0-beta3 works as expected?

**Comment by martinh-pw** [comment] 2020-09-01 13:12
@jensschuppe - Hi, sorry but I don't have a confirmation for the time being. Unfortunately as I was pursuing this ticket, someone else on the team threw together a work-around that is still being used now. We've been asked to leave this as is and focus on other work. So I apologize but I can't comment on it at the moment. :(

**Comment by jensschuppe** [comment] 2021-09-07 09:16
With #105 implementing a mitigation and the mentioned core PR being merged, I'll close this issue.

**Closed by jensschuppe** 2021-09-07 09:16 UTC
Labels: bug, important
