### ISSUE TITLE
WP: namespace for tokens used in donation receipts-templates not available

### ISSUE THREAD

**Issue by pf030** [systopia/de.systopia.donrec#62] opened 2018-06-15 08:17 UTC
Under Wordpress with CiviCRM 4.7x and higher we have encountered the following problem:

**The Smarty variables from the namespace of the extension ($contributor.xxx) are not available/filled when generating donation receipt PDFs. This makes the extension unusable under the mentioned environement.**

**We suspect it's a bug.**

Can anyone confirm?

Could the developers have a look on it please?

**Comment by systopia** [comment] 2018-06-15 09:19
Thanks for reporting @pf030 

We don't have any client using the extension on Wordpress, sorry.

@all: can anyone confirm this?

**Comment by jensschuppe** [comment] 2020-02-05 08:41
We could not reproduce this, so closing.

**Closed by jensschuppe** 2020-02-05 08:41 UTC
Labels: Wordpress, needs funding
