### ISSUE TITLE
WP: Extensions call to PDF generator causes errors when inserting images to the donation receipt-templates

### ISSUE THREAD

**Issue by pf030** [systopia/de.systopia.donrec#61] opened 2018-06-15 08:12 UTC
Under Wordpress with CiviCRM 4.7x and higher we have encountered the following problem:

**Despite we use dom-PDF or wkhtmltopdf: the generation of donation receipts fails (hieroglyphic output) as soon as we have inserted images to the donation receipt-templates.**

**We have verified that both above mentioned PDF-generators do not cause errors when using images in other templates, e.g. for the Print & Merge-functionality. **

We can confirm this behaviour on a live system as well as on a clean test installation in the above mentioned environment

**We therefore supect it's a bug** under the above mentioned environment.

Can anyone confirm?

Could the developers have a look on it please?

**Comment by systopia** [comment] 2018-06-15 09:18
Thanks for reporting @pf030. 
@all: Can any Wordpress user confirm this?

**Comment by jensschuppe** [comment] 2020-02-05 08:41
We can't reproduce this, so closing.

**Comment by Detsieber** [comment] 2020-11-20 15:09
This issue is still reproducable!
Could you please re-open?

**Comment by jensschuppe** [comment] 2020-11-25 14:38
@Detsieber Could you provide steps to reproduce this on a clean installation?

**Comment by Detsieber** [comment] 2020-11-25 17:35
Steps to reproduce on a clean install (CiviCRM on Wordpress):

1. Donation receipts profile: edit
2. Enter an image into the receipt template, e.g.:
<div class="logo-header"><img alt="logo" src="https://systopia.de/sites/default/files/SYSTOPIA%20Logo%20HD_0.png" /></div>
3. Check: "PDF Originale speichern" / "Store original *.pdf files"
4. Create a contribution
5. Create new donation receipt: Issue donation receipt(s) (NOT a test run), Download PDF
6. Open the donation receipt pdf with file manager in the download directory -> this should work
7. View donation receipt, click "Download" > this should work, since the original pdf file is stored
8. Click "create copy", click "view": -> this will fail and display random characters on the screen

**Comment by Detsieber** [comment] 2021-02-20 10:08
I checked today with CiviCRM 5.34.0, Donrec 2.0, Wordpress 5.6.1:
This still doesn't work.

This bug makes it impossible to create and download a "copy" of donation receipt.

**Comment by being-peace** [comment] 2021-03-28 19:52
I checked today with Wordpress 5.6.2, CiviCRM 5.32.2, DonRec Master  and had no problem to create and download the "copy" with "KOPIE" watermark.

**Comment by Detsieber** [comment] 2021-03-29 07:14
As far as I observed, the problems only happen when there are images
included in the pdf file.


Am 28.03.21 um 21:52 schrieb Polzin:

**Comment by being-peace** [comment] 2021-03-29 07:59
I had an image included (with <img src="https://..." width="150px">).

**Comment by BenediktMagnus** [comment] 2021-04-12 09:31
This bug is fixed in #122, already merged to master but not in the newest release yet.

**Comment by jensschuppe** [comment] 2021-04-12 09:59
As @being-peace already confirmed, this works with the current `master` branch. I'm thus closing this as a duplicate of #122.

**Closed by jensschuppe** 2021-04-12 09:59 UTC
Labels: Wordpress, bug, duplicate
